### ISSUE TITLE
RE: "This Table" Under Connecting to an Appliance

### ISSUE THREAD

**Issue by silver2row** [GEMakers/green-bean#7]
Hello,

I noticed that the hyperlink for the "This Table" link does not work. Please send guidance for working with connecting to appliances. 

Sincerely,

Seth

**Comment by sipvoip** [comment]
Anyone have an updated list of appliances Green Bean works with? Building a new house and would like to tie them all into my home automation system.

**Comment by bakerface** [comment]
I have updated the documentation with a list of [supported appliances](https://github.com/GEMakers/green-bean/blob/master/SupportedAppliances.md). This should help address the issue of whether an appliance is supported.
